"""
bootstrap_significance.py

Bootstrap significance analysis for the regime-aware sector rotation project.

The goal is to test whether the full-sample outperformance of the best
strategy is robust or whether it may be compatible with sampling noise.

The script uses a paired circular block bootstrap:

1. Load the monthly return matrix generated by compare_strategies.py.
2. Compare one target strategy against several benchmarks.
3. Resample monthly returns in blocks, preserving the cross-sectional
   relation between the strategy and the benchmark.
4. Compute confidence intervals for performance differences.

Run from the project root with:

    python src/haa/bootstrap_significance.py
"""

from pathlib import Path
import sys

import numpy as np
import pandas as pd


# ============================================================
# Imports
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SRC_DIR = PROJECT_ROOT / "src"

if str(SRC_DIR) not in sys.path:
    sys.path.append(str(SRC_DIR))

from common.metrics import (
    compute_cagr,
    compute_annualized_return,
    compute_annualized_volatility,
    compute_sharpe_ratio,
)


# ============================================================
# Configuration
# ============================================================

DATA_DIR = Path("data")

COMPARISON_RETURNS_PATH = DATA_DIR / "strategy_comparison_returns.csv"

BOOTSTRAP_SUMMARY_PATH = DATA_DIR / "bootstrap_significance_summary.csv"
BOOTSTRAP_DISTRIBUTIONS_PATH = DATA_DIR / "bootstrap_significance_distributions.csv"

PERIODS_PER_YEAR = 12

TARGET_STRATEGY = "Sector Top-2 SHY Net"

BENCHMARKS = [
    "SPY Buy and Hold",
    "VTI Buy and Hold",
    "HAA Market-Cap Net",
    "Sector Top-2 Net",
    "Sector Top-1 Net",
]

N_BOOTSTRAP = 10_000
BLOCK_LENGTH = 6
RANDOM_SEED = 42


# ============================================================
# Loading
# ============================================================

def load_comparison_returns(
    path: Path = COMPARISON_RETURNS_PATH,
) -> pd.DataFrame:
    """
    Load the unified return matrix.

    Parameters
    ----------
    path:
        CSV generated by compare_strategies.py.

    Returns
    -------
    pd.DataFrame
        Monthly return matrix.
    """
    if not path.exists():
        raise FileNotFoundError(
            f"Missing file: {path}. "
            "Run python src/haa/compare_strategies.py first."
        )

    returns = pd.read_csv(path, index_col=0, parse_dates=True)

    if returns.empty:
        raise ValueError("Comparison returns file is empty.")

    required_columns = [TARGET_STRATEGY] + BENCHMARKS
    missing = [col for col in required_columns if col not in returns.columns]

    if missing:
        raise ValueError(f"Missing expected columns: {missing}")

    return returns[required_columns].dropna()


# ============================================================
# Metric computation
# ============================================================

def compute_metrics(
    returns: pd.Series,
) -> dict[str, float]:
    """
    Compute standard performance metrics.

    Parameters
    ----------
    returns:
        Monthly simple return series.

    Returns
    -------
    dict[str, float]
        Performance metrics.
    """
    return {
        "cagr": compute_cagr(
            returns=returns,
            periods_per_year=PERIODS_PER_YEAR,
        ),
        "annualized_return": compute_annualized_return(
            returns=returns,
            periods_per_year=PERIODS_PER_YEAR,
        ),
        "annualized_volatility": compute_annualized_volatility(
            returns=returns,
            periods_per_year=PERIODS_PER_YEAR,
        ),
        "sharpe_ratio": compute_sharpe_ratio(
            returns=returns,
            periods_per_year=PERIODS_PER_YEAR,
            annual_risk_free_rate=0.0,
        ),
    }


def compute_difference_metrics(
    returns: pd.DataFrame,
    strategy: str,
    benchmark: str,
) -> dict[str, float]:
    """
    Compute strategy-minus-benchmark metric differences.

    Parameters
    ----------
    returns:
        Return matrix containing strategy and benchmark columns.
    strategy:
        Strategy column.
    benchmark:
        Benchmark column.

    Returns
    -------
    dict[str, float]
        Difference metrics.
    """
    strategy_metrics = compute_metrics(returns[strategy])
    benchmark_metrics = compute_metrics(returns[benchmark])

    differences = {
        "diff_cagr": strategy_metrics["cagr"] - benchmark_metrics["cagr"],
        "diff_annualized_return": (
            strategy_metrics["annualized_return"]
            - benchmark_metrics["annualized_return"]
        ),
        "diff_annualized_volatility": (
            strategy_metrics["annualized_volatility"]
            - benchmark_metrics["annualized_volatility"]
        ),
        "diff_sharpe_ratio": (
            strategy_metrics["sharpe_ratio"]
            - benchmark_metrics["sharpe_ratio"]
        ),
        "mean_monthly_excess_return": (
            returns[strategy] - returns[benchmark]
        ).mean(),
    }

    return differences


# ============================================================
# Circular block bootstrap
# ============================================================

def circular_block_indices(
    n_observations: int,
    block_length: int,
    rng: np.random.Generator,
) -> np.ndarray:
    """
    Generate circular block bootstrap indices.

    Parameters
    ----------
    n_observations:
        Number of observations in the original sample.
    block_length:
        Length of each resampled block.
    rng:
        NumPy random generator.

    Returns
    -------
    np.ndarray
        Bootstrap indices of length n_observations.
    """
    if n_observations <= 0:
        raise ValueError("n_observations must be positive.")

    if block_length <= 0:
        raise ValueError("block_length must be positive.")

    indices = []

    while len(indices) < n_observations:
        start = rng.integers(0, n_observations)

        block = [
            (start + offset) % n_observations
            for offset in range(block_length)
        ]

        indices.extend(block)

    return np.array(indices[:n_observations])


def bootstrap_pair(
    returns: pd.DataFrame,
    strategy: str,
    benchmark: str,
    n_bootstrap: int = N_BOOTSTRAP,
    block_length: int = BLOCK_LENGTH,
    seed: int = RANDOM_SEED,
) -> tuple[pd.DataFrame, dict[str, float]]:
    """
    Bootstrap metric differences for one strategy-benchmark pair.

    Parameters
    ----------
    returns:
        Return matrix.
    strategy:
        Strategy column.
    benchmark:
        Benchmark column.
    n_bootstrap:
        Number of bootstrap samples.
    block_length:
        Length of resampled blocks.
    seed:
        Random seed.

    Returns
    -------
    tuple[pd.DataFrame, dict[str, float]]
        Bootstrap distribution and observed metric differences.
    """
    pair_returns = returns[[strategy, benchmark]].dropna()

    if pair_returns.empty:
        raise ValueError(f"No common returns for {strategy} and {benchmark}.")

    observed = compute_difference_metrics(
        returns=pair_returns,
        strategy=strategy,
        benchmark=benchmark,
    )

    rng = np.random.default_rng(seed)
    n_observations = len(pair_returns)

    rows = []

    for sample_id in range(n_bootstrap):
        indices = circular_block_indices(
            n_observations=n_observations,
            block_length=block_length,
            rng=rng,
        )

        sample = pair_returns.iloc[indices].reset_index(drop=True)

        diffs = compute_difference_metrics(
            returns=sample,
            strategy=strategy,
            benchmark=benchmark,
        )

        diffs["sample_id"] = sample_id
        diffs["benchmark"] = benchmark

        rows.append(diffs)

    distribution = pd.DataFrame(rows)

    return distribution, observed


# ============================================================
# Summary
# ============================================================

def summarize_bootstrap_distribution(
    distribution: pd.DataFrame,
    observed: dict[str, float],
    benchmark: str,
) -> pd.DataFrame:
    """
    Summarize bootstrap confidence intervals.

    Parameters
    ----------
    distribution:
        Bootstrap metric distribution.
    observed:
        Observed metric differences.
    benchmark:
        Benchmark name.

    Returns
    -------
    pd.DataFrame
        Summary table.
    """
    metric_columns = [
        "diff_cagr",
        "diff_annualized_return",
        "diff_annualized_volatility",
        "diff_sharpe_ratio",
        "mean_monthly_excess_return",
    ]

    rows = []

    for metric in metric_columns:
        values = distribution[metric].dropna()

        ci_lower = values.quantile(0.025)
        ci_upper = values.quantile(0.975)

        probability_positive = float((values > 0).mean())
        probability_negative = float((values < 0).mean())

        p_two_sided_zero = 2.0 * min(
            probability_positive,
            probability_negative,
        )
        p_two_sided_zero = min(p_two_sided_zero, 1.0)

        if metric == "diff_annualized_volatility":
            probability_favorable = probability_negative
            favorable_direction = "lower"
        else:
            probability_favorable = probability_positive
            favorable_direction = "higher"

        if ci_lower > 0 and metric != "diff_annualized_volatility":
            interpretation = "positive_difference_ci_excludes_zero"
        elif ci_upper < 0 and metric == "diff_annualized_volatility":
            interpretation = "lower_volatility_ci_excludes_zero"
        elif ci_lower <= 0 <= ci_upper:
            interpretation = "ci_includes_zero"
        else:
            interpretation = "unfavorable_difference_ci_excludes_zero"

        rows.append(
            {
                "target_strategy": TARGET_STRATEGY,
                "benchmark": benchmark,
                "metric": metric,
                "observed_difference": observed[metric],
                "ci_2_5": ci_lower,
                "ci_97_5": ci_upper,
                "probability_positive": probability_positive,
                "probability_negative": probability_negative,
                "probability_favorable": probability_favorable,
                "favorable_direction": favorable_direction,
                "p_two_sided_zero": p_two_sided_zero,
                "interpretation": interpretation,
            }
        )

    return pd.DataFrame(rows)


def run_bootstrap_significance_analysis(
    returns: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Run bootstrap significance analysis for all benchmarks.

    Parameters
    ----------
    returns:
        Return matrix.

    Returns
    -------
    tuple[pd.DataFrame, pd.DataFrame]
        Summary table and full bootstrap distributions.
    """
    summary_frames = []
    distribution_frames = []

    for i, benchmark in enumerate(BENCHMARKS):
        print()
        print(f"Bootstrapping {TARGET_STRATEGY} vs {benchmark}")

        distribution, observed = bootstrap_pair(
            returns=returns,
            strategy=TARGET_STRATEGY,
            benchmark=benchmark,
            n_bootstrap=N_BOOTSTRAP,
            block_length=BLOCK_LENGTH,
            seed=RANDOM_SEED + i,
        )

        summary = summarize_bootstrap_distribution(
            distribution=distribution,
            observed=observed,
            benchmark=benchmark,
        )

        summary_frames.append(summary)
        distribution_frames.append(distribution)

    summary_table = pd.concat(summary_frames, axis=0, ignore_index=True)
    distributions = pd.concat(distribution_frames, axis=0, ignore_index=True)

    return summary_table, distributions


# ============================================================
# Display
# ============================================================

def format_summary_for_display(
    summary: pd.DataFrame,
) -> pd.DataFrame:
    """
    Format the bootstrap summary for terminal display.

    Parameters
    ----------
    summary:
        Raw bootstrap summary.

    Returns
    -------
    pd.DataFrame
        Formatted summary.
    """
    formatted = summary.copy()

    def format_difference(row: pd.Series, column: str) -> str:
        value = row[column]

        if row["metric"] == "diff_sharpe_ratio":
            return f"{value:.3f}"

        return f"{100 * value:.2f}%"

    for col in ["observed_difference", "ci_2_5", "ci_97_5"]:
        if col in formatted.columns:
            formatted[col] = formatted.apply(
                lambda row: format_difference(row, col),
                axis=1,
            )

    probability_columns = [
        "probability_positive",
        "probability_negative",
        "probability_favorable",
        "p_two_sided_zero",
    ]

    for col in probability_columns:
        if col in formatted.columns:
            formatted[col] = formatted[col].map(lambda x: f"{x:.3f}")

    return formatted
# ============================================================
# Main
# ============================================================

def main() -> None:
    """
    Run bootstrap significance analysis.
    """
    print("=" * 80)
    print("Bootstrap significance analysis")
    print("=" * 80)

    returns = load_comparison_returns()

    print()
    print("Return matrix loaded:")
    print(returns.tail())
    print()
    print(f"Shape: {returns.shape}")
    print(f"Date range: {returns.index.min().date()} to {returns.index.max().date()}")

    summary, distributions = run_bootstrap_significance_analysis(
        returns=returns,
    )

    DATA_DIR.mkdir(parents=True, exist_ok=True)

    summary.to_csv(BOOTSTRAP_SUMMARY_PATH, index=False)
    distributions.to_csv(BOOTSTRAP_DISTRIBUTIONS_PATH, index=False)

    print()
    print("Bootstrap summary:")
    display_columns = [
        "benchmark",
        "metric",
        "observed_difference",
        "ci_2_5",
        "ci_97_5",
        "probability_favorable",
        "p_two_sided_zero",
        "interpretation",
    ]
    print(
        format_summary_for_display(summary[display_columns])
        .to_string(index=False)
    )

    print()
    print("Saved outputs:")
    print(f"- {BOOTSTRAP_SUMMARY_PATH}")
    print(f"- {BOOTSTRAP_DISTRIBUTIONS_PATH}")

    print()
    print("Done.")


if __name__ == "__main__":
    main()