"""
compare_strategies.py

Strategy comparison script.

This file compares:
- HAA market-cap replication;
- Sector rotation Top-1;
- Sector rotation Top-2;
- VTI buy and hold;
- SPY buy and hold.

It loads the return and weight files generated by:
    python src/haa/replication.py
    python src/haa/sector_rotation.py
    python src/haa/sector_rotation_topk.py

Run from the project root with:

    python src/haa/compare_strategies.py
"""

from pathlib import Path
import sys

import matplotlib.pyplot as plt
import pandas as pd


# Make imports robust when running the file directly from the project root.
PROJECT_ROOT = Path(__file__).resolve().parents[2]
SRC_DIR = PROJECT_ROOT / "src"

if str(SRC_DIR) not in sys.path:
    sys.path.append(str(SRC_DIR))

from common.metrics import (
    compute_turnover,
    compute_performance_summary,
    format_performance_summary,
    compute_equity_curve,
    compute_drawdown,
)


# ============================================================
# Paths
# ============================================================

DATA_DIR = Path("data")
FIGURES_DIR = Path("figures")

HAA_RETURNS_PATH = DATA_DIR / "haa_replication_returns.csv"
HAA_WEIGHTS_PATH = DATA_DIR / "haa_replication_weights.csv"

SECTOR_TOP1_RETURNS_PATH = DATA_DIR / "sector_rotation_returns.csv"
SECTOR_TOP1_WEIGHTS_PATH = DATA_DIR / "sector_rotation_weights.csv"

SECTOR_TOP2_RETURNS_PATH = DATA_DIR / "sector_rotation_top2_returns.csv"
SECTOR_TOP2_WEIGHTS_PATH = DATA_DIR / "sector_rotation_top2_weights.csv"

COMPARISON_RETURNS_PATH = DATA_DIR / "strategy_comparison_returns.csv"
COMPARISON_SUMMARY_PATH = DATA_DIR / "strategy_comparison_summary.csv"

PERIODS_PER_YEAR = 12


# ============================================================
# Loading utilities
# ============================================================

def load_return_column(
    path: Path,
    column: str,
    new_name: str,
) -> pd.Series:
    """
    Load a single return column from a CSV file.
    """
    if not path.exists():
        raise FileNotFoundError(
            f"Missing file: {path}. "
            "Run the corresponding strategy script first."
        )

    returns = pd.read_csv(path, index_col=0, parse_dates=True)

    if column not in returns.columns:
        raise ValueError(
            f"Column '{column}' not found in {path}. "
            f"Available columns: {list(returns.columns)}"
        )

    series = returns[column].copy()
    series.name = new_name

    return series


def load_weights(path: Path) -> pd.DataFrame:
    """
    Load strategy weights from a CSV file.
    """
    if not path.exists():
        raise FileNotFoundError(
            f"Missing file: {path}. "
            "Run the corresponding strategy script first."
        )

    weights = pd.read_csv(path, index_col=0, parse_dates=True)
    return weights


# ============================================================
# Comparison construction
# ============================================================

def build_comparison_returns() -> pd.DataFrame:
    """
    Build a unified return matrix for all strategies and benchmarks.
    """
    haa_net = load_return_column(
        path=HAA_RETURNS_PATH,
        column="HAA Net",
        new_name="HAA Market-Cap Net",
    )

    sector_top1_net = load_return_column(
        path=SECTOR_TOP1_RETURNS_PATH,
        column="Sector Rotation Net",
        new_name="Sector Top-1 Net",
    )

    sector_top2_net = load_return_column(
        path=SECTOR_TOP2_RETURNS_PATH,
        column="Sector Rotation Top-2 Net",
        new_name="Sector Top-2 Net",
    )

    vti = load_return_column(
        path=SECTOR_TOP2_RETURNS_PATH,
        column="VTI Buy and Hold",
        new_name="VTI Buy and Hold",
    )

    spy = load_return_column(
        path=SECTOR_TOP2_RETURNS_PATH,
        column="SPY Buy and Hold",
        new_name="SPY Buy and Hold",
    )

    comparison_returns = pd.concat(
        [
            haa_net,
            sector_top1_net,
            sector_top2_net,
            vti,
            spy,
        ],
        axis=1,
    )

    comparison_returns = comparison_returns.dropna()

    return comparison_returns


def build_turnover_map(
    comparison_returns: pd.DataFrame,
) -> dict[str, pd.Series | None]:
    """
    Build turnover series for strategies.

    Benchmarks have no turnover in this comparison.
    """
    haa_turnover = compute_turnover(load_weights(HAA_WEIGHTS_PATH))
    sector_top1_turnover = compute_turnover(load_weights(SECTOR_TOP1_WEIGHTS_PATH))
    sector_top2_turnover = compute_turnover(load_weights(SECTOR_TOP2_WEIGHTS_PATH))

    turnover_map = {
        "HAA Market-Cap Net": haa_turnover.reindex(comparison_returns.index).fillna(0.0),
        "Sector Top-1 Net": sector_top1_turnover.reindex(comparison_returns.index).fillna(0.0),
        "Sector Top-2 Net": sector_top2_turnover.reindex(comparison_returns.index).fillna(0.0),
        "VTI Buy and Hold": None,
        "SPY Buy and Hold": None,
    }

    return turnover_map


def build_comparison_summary(
    comparison_returns: pd.DataFrame,
) -> pd.DataFrame:
    """
    Build a unified performance summary for all strategies.
    """
    turnover_map = build_turnover_map(comparison_returns)

    rows = {}

    for column in comparison_returns.columns:
        rows[column] = compute_performance_summary(
            returns=comparison_returns[column],
            periods_per_year=PERIODS_PER_YEAR,
            turnover=turnover_map[column],
        )

    summary = pd.DataFrame(rows).T

    return summary


# ============================================================
# Plotting utilities
# ============================================================

def save_figure(path: Path) -> None:
    """
    Save current matplotlib figure.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(path, dpi=300)
    plt.close()


def plot_cumulative_performance(
    returns: pd.DataFrame,
    output_path: Path,
) -> None:
    """
    Plot cumulative performance.
    """
    equity_curves = pd.DataFrame(
        {
            column: compute_equity_curve(returns[column])
            for column in returns.columns
        }
    )

    plt.figure(figsize=(10, 6))

    for column in equity_curves.columns:
        plt.plot(equity_curves.index, equity_curves[column], label=column)

    plt.title("Strategy Comparison: Cumulative Performance")
    plt.xlabel("Date")
    plt.ylabel("Growth of $1")
    plt.legend()
    plt.grid(True, alpha=0.3)

    save_figure(output_path)


def plot_drawdowns(
    returns: pd.DataFrame,
    output_path: Path,
) -> None:
    """
    Plot drawdowns.
    """
    equity_curves = pd.DataFrame(
        {
            column: compute_equity_curve(returns[column])
            for column in returns.columns
        }
    )

    drawdowns = pd.DataFrame(
        {
            column: compute_drawdown(equity_curves[column])
            for column in equity_curves.columns
        }
    )

    plt.figure(figsize=(10, 6))

    for column in drawdowns.columns:
        plt.plot(drawdowns.index, drawdowns[column], label=column)

    plt.title("Strategy Comparison: Drawdowns")
    plt.xlabel("Date")
    plt.ylabel("Drawdown")
    plt.legend()
    plt.grid(True, alpha=0.3)

    save_figure(output_path)


def plot_metric_bar(
    summary: pd.DataFrame,
    metric: str,
    title: str,
    ylabel: str,
    output_path: Path,
) -> None:
    """
    Plot one metric as a bar chart.
    """
    if metric not in summary.columns:
        raise ValueError(f"Metric '{metric}' not found in summary.")

    values = summary[metric].copy()

    plt.figure(figsize=(9, 5))
    plt.bar(values.index, values.values)

    plt.title(title)
    plt.ylabel(ylabel)
    plt.xticks(rotation=30, ha="right")
    plt.grid(True, axis="y", alpha=0.3)

    save_figure(output_path)


def generate_comparison_figures(
    returns: pd.DataFrame,
    summary: pd.DataFrame,
) -> None:
    """
    Generate all comparison figures.
    """
    plot_cumulative_performance(
        returns=returns,
        output_path=FIGURES_DIR / "strategy_comparison_cumulative_performance.png",
    )

    plot_drawdowns(
        returns=returns,
        output_path=FIGURES_DIR / "strategy_comparison_drawdowns.png",
    )

    plot_metric_bar(
        summary=summary,
        metric="cagr",
        title="Strategy Comparison: CAGR",
        ylabel="CAGR",
        output_path=FIGURES_DIR / "strategy_comparison_cagr.png",
    )

    plot_metric_bar(
        summary=summary,
        metric="annualized_volatility",
        title="Strategy Comparison: Annualized Volatility",
        ylabel="Annualized volatility",
        output_path=FIGURES_DIR / "strategy_comparison_volatility.png",
    )

    plot_metric_bar(
        summary=summary,
        metric="sharpe_ratio",
        title="Strategy Comparison: Sharpe Ratio",
        ylabel="Sharpe ratio",
        output_path=FIGURES_DIR / "strategy_comparison_sharpe.png",
    )

    plot_metric_bar(
        summary=summary,
        metric="max_drawdown",
        title="Strategy Comparison: Maximum Drawdown",
        ylabel="Maximum drawdown",
        output_path=FIGURES_DIR / "strategy_comparison_max_drawdown.png",
    )


# ============================================================
# Display helpers
# ============================================================

def print_ranking(summary: pd.DataFrame) -> None:
    """
    Print strategy rankings.
    """
    print()
    print("Ranking by CAGR:")
    print(summary["cagr"].sort_values(ascending=False).map(lambda x: f"{100 * x:.2f}%"))

    print()
    print("Ranking by Sharpe ratio:")
    print(summary["sharpe_ratio"].sort_values(ascending=False).map(lambda x: f"{x:.2f}"))

    print()
    print("Ranking by maximum drawdown:")
    print(summary["max_drawdown"].sort_values(ascending=False).map(lambda x: f"{100 * x:.2f}%"))


# ============================================================
# Main
# ============================================================

def main() -> None:
    """
    Run the full comparison.
    """
    print("=" * 80)
    print("Strategy comparison")
    print("=" * 80)

    returns = build_comparison_returns()
    summary = build_comparison_summary(returns)

    DATA_DIR.mkdir(parents=True, exist_ok=True)

    returns.to_csv(COMPARISON_RETURNS_PATH)
    summary.to_csv(COMPARISON_SUMMARY_PATH)

    generate_comparison_figures(
        returns=returns,
        summary=summary,
    )

    print()
    print("Comparison returns:")
    print(returns.tail())

    print()
    print("Raw comparison summary:")
    print(summary)

    print()
    print("Formatted comparison summary:")
    print(format_performance_summary(summary))

    print_ranking(summary)

    print()
    print("Saved outputs:")
    print(f"- {COMPARISON_RETURNS_PATH}")
    print(f"- {COMPARISON_SUMMARY_PATH}")

    print()
    print("Saved figures:")
    print(f"- {FIGURES_DIR / 'strategy_comparison_cumulative_performance.png'}")
    print(f"- {FIGURES_DIR / 'strategy_comparison_drawdowns.png'}")
    print(f"- {FIGURES_DIR / 'strategy_comparison_cagr.png'}")
    print(f"- {FIGURES_DIR / 'strategy_comparison_volatility.png'}")
    print(f"- {FIGURES_DIR / 'strategy_comparison_sharpe.png'}")
    print(f"- {FIGURES_DIR / 'strategy_comparison_max_drawdown.png'}")

    print()
    print("Done.")


if __name__ == "__main__":
    main()