"""
oos_validation.py

In-sample / out-of-sample validation for the strategy comparison.

This script reads the return files generated by:

    python src/haa/compare_strategies.py

and evaluates each strategy on three periods:

1. Full sample:
       2005-01-31 to 2025-12-31

2. In-sample:
       2005-01-31 to 2015-12-31

3. Out-of-sample:
       2016-01-31 to 2025-12-31

The goal is not to claim that the strategy has been fully optimized
out-of-sample, but to reduce the risk of pure full-sample data mining.

Run from the project root with:

    python src/haa/oos_validation.py
"""

from pathlib import Path
import sys

import pandas as pd


# Make imports robust when running the file directly from the project root.
PROJECT_ROOT = Path(__file__).resolve().parents[2]
SRC_DIR = PROJECT_ROOT / "src"

if str(SRC_DIR) not in sys.path:
    sys.path.append(str(SRC_DIR))

from common.metrics import (
    compute_turnover,
    compute_performance_summary,
    format_performance_summary,
)


# ============================================================
# Paths
# ============================================================

DATA_DIR = Path("data")

COMPARISON_RETURNS_PATH = DATA_DIR / "strategy_comparison_returns.csv"

HAA_WEIGHTS_PATH = DATA_DIR / "haa_replication_weights.csv"
SECTOR_TOP1_WEIGHTS_PATH = DATA_DIR / "sector_rotation_weights.csv"
SECTOR_TOP2_WEIGHTS_PATH = DATA_DIR / "sector_rotation_top2_weights.csv"
SECTOR_TOP2_SHY_WEIGHTS_PATH = DATA_DIR / "sector_rotation_top2_shy_weights.csv"

OOS_SUMMARY_OUTPUT_PATH = DATA_DIR / "oos_validation_summary.csv"

PERIODS_PER_YEAR = 12


# ============================================================
# Validation periods
# ============================================================

VALIDATION_PERIODS = {
    "Full Sample": ("2005-01-31", "2025-12-31"),
    "In-Sample": ("2005-01-31", "2015-12-31"),
    "Out-of-Sample": ("2016-01-31", "2025-12-31"),
}


# ============================================================
# Loading utilities
# ============================================================

def load_returns(path: Path = COMPARISON_RETURNS_PATH) -> pd.DataFrame:
    """
    Load the unified return matrix produced by compare_strategies.py.

    Parameters
    ----------
    path:
        CSV file containing strategy and benchmark returns.

    Returns
    -------
    pd.DataFrame
        Return matrix indexed by date.
    """
    if not path.exists():
        raise FileNotFoundError(
            f"Missing file: {path}. "
            "Run python src/haa/compare_strategies.py first."
        )

    returns = pd.read_csv(path, index_col=0, parse_dates=True)

    if returns.empty:
        raise ValueError("Comparison return file is empty.")

    return returns


def load_weights(path: Path) -> pd.DataFrame:
    """
    Load strategy weights.

    Parameters
    ----------
    path:
        CSV file containing strategy weights.

    Returns
    -------
    pd.DataFrame
        Weight matrix indexed by date.
    """
    if not path.exists():
        raise FileNotFoundError(
            f"Missing file: {path}. "
            "Run the corresponding strategy script first."
        )

    weights = pd.read_csv(path, index_col=0, parse_dates=True)

    if weights.empty:
        raise ValueError(f"Weight file is empty: {path}")

    return weights


def build_turnover_map() -> dict[str, pd.Series | None]:
    """
    Build a turnover series for each dynamic strategy.

    Benchmarks have no turnover in this analysis.

    Returns
    -------
    dict[str, pd.Series | None]
        Mapping from strategy name to turnover series.
    """
    turnover_map = {
        "HAA Market-Cap Net": compute_turnover(
            load_weights(HAA_WEIGHTS_PATH)
        ),
        "Sector Top-1 Net": compute_turnover(
            load_weights(SECTOR_TOP1_WEIGHTS_PATH)
        ),
        "Sector Top-2 Net": compute_turnover(
            load_weights(SECTOR_TOP2_WEIGHTS_PATH)
        ),
        "Sector Top-2 SHY Net": compute_turnover(
            load_weights(SECTOR_TOP2_SHY_WEIGHTS_PATH)
        ),
        "VTI Buy and Hold": None,
        "SPY Buy and Hold": None,
    }

    return turnover_map


# ============================================================
# Period utilities
# ============================================================

def slice_period(
    series_or_frame: pd.Series | pd.DataFrame,
    start_date: str,
    end_date: str,
) -> pd.Series | pd.DataFrame:
    """
    Slice a Series or DataFrame over a date range.

    Parameters
    ----------
    series_or_frame:
        Series or DataFrame indexed by date.
    start_date:
        Start date.
    end_date:
        End date.

    Returns
    -------
    pd.Series | pd.DataFrame
        Sliced object.
    """
    return series_or_frame.loc[
        (series_or_frame.index >= start_date)
        & (series_or_frame.index <= end_date)
    ]


def compute_period_summary(
    returns: pd.DataFrame,
    turnover_map: dict[str, pd.Series | None],
    start_date: str,
    end_date: str,
) -> pd.DataFrame:
    """
    Compute performance summaries for all strategies over one period.

    Parameters
    ----------
    returns:
        Unified return matrix.
    turnover_map:
        Mapping from strategy name to turnover.
    start_date:
        Start date.
    end_date:
        End date.

    Returns
    -------
    pd.DataFrame
        Performance summary for the selected period.
    """
    period_returns = slice_period(
        series_or_frame=returns,
        start_date=start_date,
        end_date=end_date,
    )

    if not isinstance(period_returns, pd.DataFrame):
        raise TypeError("period_returns should be a DataFrame.")

    period_returns = period_returns.dropna()

    if period_returns.empty:
        raise ValueError(
            f"No returns available between {start_date} and {end_date}."
        )

    rows = {}

    for strategy in period_returns.columns:
        turnover = turnover_map.get(strategy)

        if turnover is not None:
            period_turnover = slice_period(
                series_or_frame=turnover,
                start_date=start_date,
                end_date=end_date,
            )

            if not isinstance(period_turnover, pd.Series):
                raise TypeError("period_turnover should be a Series.")

            period_turnover = period_turnover.reindex(
                period_returns.index
            ).fillna(0.0)
        else:
            period_turnover = None

        rows[strategy] = compute_performance_summary(
            returns=period_returns[strategy],
            periods_per_year=PERIODS_PER_YEAR,
            turnover=period_turnover,
        )

    summary = pd.DataFrame(rows).T

    return summary


def build_oos_validation_summary(
    returns: pd.DataFrame,
) -> pd.DataFrame:
    """
    Build the full in-sample / out-of-sample validation summary.

    Parameters
    ----------
    returns:
        Unified return matrix.

    Returns
    -------
    pd.DataFrame
        Multi-index summary with levels:
        - sample;
        - strategy.
    """
    turnover_map = build_turnover_map()

    all_summaries = []

    for sample_name, (start_date, end_date) in VALIDATION_PERIODS.items():
        summary = compute_period_summary(
            returns=returns,
            turnover_map=turnover_map,
            start_date=start_date,
            end_date=end_date,
        )

        summary.insert(0, "sample", sample_name)
        summary.insert(1, "start_date", start_date)
        summary.insert(2, "end_date", end_date)
        summary.insert(3, "strategy", summary.index)

        all_summaries.append(summary.reset_index(drop=True))

    validation_summary = pd.concat(all_summaries, axis=0, ignore_index=True)

    validation_summary = validation_summary.set_index(
        ["sample", "strategy"]
    )

    return validation_summary


# ============================================================
# Display helpers
# ============================================================

def print_sample_summary(
    validation_summary: pd.DataFrame,
    sample_name: str,
) -> None:
    """
    Print formatted summary for one sample.

    Parameters
    ----------
    validation_summary:
        Multi-index validation summary.
    sample_name:
        Sample name to print.
    """
    sample_summary = validation_summary.loc[sample_name].copy()

    # Keep only performance metrics in display.
    display_summary = sample_summary.drop(
        columns=["start_date", "end_date"],
        errors="ignore",
    )

    print()
    print("=" * 80)
    print(sample_name)
    print("=" * 80)
    print(format_performance_summary(display_summary))

    print()
    print("Ranking by CAGR:")
    print(
        sample_summary["cagr"]
        .sort_values(ascending=False)
        .map(lambda x: f"{100 * x:.2f}%")
    )

    print()
    print("Ranking by Sharpe ratio:")
    print(
        sample_summary["sharpe_ratio"]
        .sort_values(ascending=False)
        .map(lambda x: f"{x:.2f}")
    )

    print()
    print("Ranking by maximum drawdown:")
    print(
        sample_summary["max_drawdown"]
        .sort_values(ascending=False)
        .map(lambda x: f"{100 * x:.2f}%")
    )


def print_oos_focus(validation_summary: pd.DataFrame) -> None:
    """
    Print a compact focus on the out-of-sample period.
    """
    oos = validation_summary.loc["Out-of-Sample"].copy()

    print()
    print("=" * 80)
    print("Out-of-sample focus")
    print("=" * 80)

    key_columns = [
        "cagr",
        "annualized_volatility",
        "sharpe_ratio",
        "max_drawdown",
    ]

    focus = oos[key_columns].copy()
    focus["cagr"] = focus["cagr"].map(lambda x: f"{100 * x:.2f}%")
    focus["annualized_volatility"] = focus["annualized_volatility"].map(
        lambda x: f"{100 * x:.2f}%"
    )
    focus["sharpe_ratio"] = focus["sharpe_ratio"].map(lambda x: f"{x:.2f}")
    focus["max_drawdown"] = focus["max_drawdown"].map(lambda x: f"{100 * x:.2f}%")

    print(focus)


# ============================================================
# Main
# ============================================================

def main() -> None:
    """
    Run the in-sample / out-of-sample validation.
    """
    print("=" * 80)
    print("In-sample / out-of-sample validation")
    print("=" * 80)

    returns = load_returns()
    validation_summary = build_oos_validation_summary(returns)

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    validation_summary.to_csv(OOS_SUMMARY_OUTPUT_PATH)

    print()
    print("Return matrix loaded:")
    print(returns.tail())
    print()
    print(f"Shape: {returns.shape}")
    print(f"Date range: {returns.index.min().date()} to {returns.index.max().date()}")

    for sample_name in VALIDATION_PERIODS:
        print_sample_summary(
            validation_summary=validation_summary,
            sample_name=sample_name,
        )

    print_oos_focus(validation_summary)

    print()
    print("Saved outputs:")
    print(f"- {OOS_SUMMARY_OUTPUT_PATH}")

    print()
    print("Done.")


if __name__ == "__main__":
    main()