"""
plot_robustness_canary.py

Generate robustness figures for the canary asset test.

This script reads the outputs generated by:

    python src/haa/robustness_canary.py

and creates figures for:
- CAGR;
- annualized volatility;
- Sharpe ratio;
- maximum drawdown;
- risk-on frequency.

Run from the project root with:

    python src/haa/plot_robustness_canary.py
"""

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


# ============================================================
# Paths
# ============================================================

DATA_DIR = Path("data")
FIGURES_DIR = Path("figures")

SUMMARY_PATH = DATA_DIR / "robustness_canary_summary.csv"
RISK_ON_PATH = DATA_DIR / "robustness_canary_risk_on_frequency.csv"

FIGURES_DIR.mkdir(parents=True, exist_ok=True)


# ============================================================
# Helpers
# ============================================================

def clean_strategy_name(name: str) -> str:
    """
    Make strategy labels shorter for plots.
    """
    return name.replace("Top-2 SHY Canary=", "Canary = ")


def load_robustness_outputs() -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Load robustness summary and risk-on frequency tables.
    """
    if not SUMMARY_PATH.exists():
        raise FileNotFoundError(
            f"Missing file: {SUMMARY_PATH}. "
            "Run python src/haa/robustness_canary.py first."
        )

    if not RISK_ON_PATH.exists():
        raise FileNotFoundError(
            f"Missing file: {RISK_ON_PATH}. "
            "Run python src/haa/robustness_canary.py first."
        )

    summary = pd.read_csv(SUMMARY_PATH, index_col=0)
    risk_on = pd.read_csv(RISK_ON_PATH, index_col=0)

    summary.index = [clean_strategy_name(name) for name in summary.index]
    risk_on.index = [clean_strategy_name(name) for name in risk_on.index]

    return summary, risk_on


def save_figure(path: Path) -> None:
    """
    Save the current matplotlib figure.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(path, dpi=300)
    plt.close()


def plot_bar_metric(
    data: pd.Series,
    title: str,
    ylabel: str,
    output_path: Path,
    percentage: bool = False,
) -> None:
    """
    Plot a bar chart for a given metric.
    """
    plt.figure(figsize=(9, 5))
    plt.bar(data.index, data.values)

    plt.title(title)
    plt.ylabel(ylabel)
    plt.xticks(rotation=30, ha="right")
    plt.grid(True, axis="y", alpha=0.3)

    if percentage:
        current_ticks = plt.gca().get_yticks()
        plt.gca().set_yticklabels([f"{100 * tick:.0f}%" for tick in current_ticks])

    save_figure(output_path)


# ============================================================
# Main plotting functions
# ============================================================

def generate_robustness_figures(
    summary: pd.DataFrame,
    risk_on: pd.DataFrame,
) -> None:
    """
    Generate all canary robustness figures.
    """
    plot_bar_metric(
        data=summary["cagr"].sort_values(ascending=False),
        title="Canary Robustness: CAGR",
        ylabel="CAGR",
        output_path=FIGURES_DIR / "robustness_canary_cagr.png",
        percentage=True,
    )

    plot_bar_metric(
        data=summary["annualized_volatility"].sort_values(ascending=True),
        title="Canary Robustness: Annualized Volatility",
        ylabel="Annualized volatility",
        output_path=FIGURES_DIR / "robustness_canary_volatility.png",
        percentage=True,
    )

    plot_bar_metric(
        data=summary["sharpe_ratio"].sort_values(ascending=False),
        title="Canary Robustness: Sharpe Ratio",
        ylabel="Sharpe ratio",
        output_path=FIGURES_DIR / "robustness_canary_sharpe.png",
        percentage=False,
    )

    plot_bar_metric(
        data=summary["max_drawdown"].sort_values(ascending=False),
        title="Canary Robustness: Maximum Drawdown",
        ylabel="Maximum drawdown",
        output_path=FIGURES_DIR / "robustness_canary_max_drawdown.png",
        percentage=True,
    )

    plot_bar_metric(
        data=risk_on["risk_on_frequency"].sort_values(ascending=False),
        title="Canary Robustness: Risk-On Frequency",
        ylabel="Risk-on frequency",
        output_path=FIGURES_DIR / "robustness_canary_risk_on_frequency.png",
        percentage=True,
    )


def main() -> None:
    """
    Generate robustness figures.
    """
    print("=" * 80)
    print("Generating canary robustness figures")
    print("=" * 80)

    summary, risk_on = load_robustness_outputs()

    print()
    print("Robustness summary:")
    print(summary)

    print()
    print("Risk-on frequencies:")
    print(risk_on)

    generate_robustness_figures(
        summary=summary,
        risk_on=risk_on,
    )

    print()
    print("Saved figures:")
    print(f"- {FIGURES_DIR / 'robustness_canary_cagr.png'}")
    print(f"- {FIGURES_DIR / 'robustness_canary_volatility.png'}")
    print(f"- {FIGURES_DIR / 'robustness_canary_sharpe.png'}")
    print(f"- {FIGURES_DIR / 'robustness_canary_max_drawdown.png'}")
    print(f"- {FIGURES_DIR / 'robustness_canary_risk_on_frequency.png'}")

    print()
    print("Done.")


if __name__ == "__main__":
    main()