"""
walk_forward_validation.py

Rolling walk-forward validation for the regime-aware sector rotation project.

This script addresses the main model-selection issue in the project:
the best full-sample strategy should not be interpreted as the strategy
that would have been selected in real time.

The procedure is:

1. Load the unified return matrix produced by compare_strategies.py.
2. For each test year, use only the previous training window.
3. Select the best strategy in-sample according to a metric.
4. Hold that selected strategy during the following year.
5. Compare the resulting honest walk-forward portfolio with fixed strategies.

Run from the project root with:

    python src/haa/walk_forward_validation.py
"""

from pathlib import Path
import sys

import pandas as pd


# ============================================================
# Imports
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SRC_DIR = PROJECT_ROOT / "src"

if str(SRC_DIR) not in sys.path:
    sys.path.append(str(SRC_DIR))

from common.metrics import (
    compute_performance_summary,
    format_performance_summary,
)


# ============================================================
# Configuration
# ============================================================

DATA_DIR = Path("data")

COMPARISON_RETURNS_PATH = DATA_DIR / "strategy_comparison_returns.csv"

WALK_FORWARD_SELECTION_PATH = DATA_DIR / "walk_forward_selection.csv"
WALK_FORWARD_RETURNS_PATH = DATA_DIR / "walk_forward_returns.csv"
WALK_FORWARD_SUMMARY_PATH = DATA_DIR / "walk_forward_summary.csv"

PERIODS_PER_YEAR = 12

TRAINING_YEARS = 10

CANDIDATE_STRATEGIES = [
    "HAA Market-Cap Net",
    "Sector Top-1 Net",
    "Sector Top-2 Net",
    "Sector Top-2 SHY Net",
]

BENCHMARKS = [
    "VTI Buy and Hold",
    "SPY Buy and Hold",
]


# ============================================================
# Loading
# ============================================================

def load_comparison_returns(
    path: Path = COMPARISON_RETURNS_PATH,
) -> pd.DataFrame:
    """
    Load the unified strategy return matrix.

    Parameters
    ----------
    path:
        Path to the CSV generated by compare_strategies.py.

    Returns
    -------
    pd.DataFrame
        Monthly return matrix.
    """
    if not path.exists():
        raise FileNotFoundError(
            f"Missing file: {path}. "
            "Run python src/haa/compare_strategies.py first."
        )

    returns = pd.read_csv(path, index_col=0, parse_dates=True)

    if returns.empty:
        raise ValueError("Comparison return file is empty.")

    missing = [
        col for col in CANDIDATE_STRATEGIES + BENCHMARKS
        if col not in returns.columns
    ]

    if missing:
        raise ValueError(f"Missing expected columns: {missing}")

    return returns.dropna()


# ============================================================
# Period utilities
# ============================================================

def slice_years(
    returns: pd.DataFrame,
    start_year: int,
    end_year: int,
) -> pd.DataFrame:
    """
    Slice a return matrix by calendar years.

    Parameters
    ----------
    returns:
        Monthly return matrix.
    start_year:
        First calendar year included.
    end_year:
        Last calendar year included.

    Returns
    -------
    pd.DataFrame
        Sliced return matrix.
    """
    mask = (
        (returns.index.year >= start_year)
        & (returns.index.year <= end_year)
    )

    return returns.loc[mask].copy()


def available_test_years(
    returns: pd.DataFrame,
    training_years: int,
) -> list[int]:
    """
    Compute the list of years that can be tested with a rolling training window.

    Parameters
    ----------
    returns:
        Monthly return matrix.
    training_years:
        Number of years used in the training window.

    Returns
    -------
    list[int]
        Test years.
    """
    years = sorted(returns.index.year.unique())

    first_year = min(years)
    last_year = max(years)

    first_test_year = first_year + training_years

    return [
        year for year in years
        if first_test_year <= year <= last_year
    ]


# ============================================================
# Selection logic
# ============================================================

def compute_metric_table(
    returns: pd.DataFrame,
    candidate_strategies: list[str],
) -> pd.DataFrame:
    """
    Compute performance metrics for candidate strategies.

    Parameters
    ----------
    returns:
        Return matrix restricted to the training sample.
    candidate_strategies:
        Strategies considered for model selection.

    Returns
    -------
    pd.DataFrame
        Performance summary indexed by strategy.
    """
    rows = {}

    for strategy in candidate_strategies:
        rows[strategy] = compute_performance_summary(
            returns=returns[strategy],
            periods_per_year=PERIODS_PER_YEAR,
            turnover=None,
        )

    return pd.DataFrame(rows).T


def select_best_strategy(
    train_returns: pd.DataFrame,
    metric: str,
    candidate_strategies: list[str] = CANDIDATE_STRATEGIES,
) -> tuple[str, pd.DataFrame]:
    """
    Select the best strategy on the training period.

    Parameters
    ----------
    train_returns:
        Training return matrix.
    metric:
        Selection metric. Usually 'sharpe_ratio' or 'cagr'.
    candidate_strategies:
        Candidate strategies.

    Returns
    -------
    tuple[str, pd.DataFrame]
        Selected strategy and full training metric table.
    """
    summary = compute_metric_table(
        returns=train_returns,
        candidate_strategies=candidate_strategies,
    )

    if metric not in summary.columns:
        raise ValueError(
            f"Metric '{metric}' not found. "
            f"Available metrics: {list(summary.columns)}"
        )

    selected_strategy = summary[metric].idxmax()

    return selected_strategy, summary


# ============================================================
# Walk-forward construction
# ============================================================

def build_walk_forward_portfolio(
    returns: pd.DataFrame,
    selection_metric: str,
    training_years: int = TRAINING_YEARS,
) -> tuple[pd.Series, pd.DataFrame]:
    """
    Build an honest walk-forward selected portfolio.

    Parameters
    ----------
    returns:
        Monthly return matrix.
    selection_metric:
        Metric used for in-sample selection.
    training_years:
        Number of calendar years in the rolling training window.

    Returns
    -------
    tuple[pd.Series, pd.DataFrame]
        Walk-forward return series and selection log.
    """
    test_years = available_test_years(
        returns=returns,
        training_years=training_years,
    )

    oos_returns = []
    selection_rows = []

    for test_year in test_years:
        train_start_year = test_year - training_years
        train_end_year = test_year - 1

        train_returns = slice_years(
            returns=returns,
            start_year=train_start_year,
            end_year=train_end_year,
        )

        test_returns = slice_years(
            returns=returns,
            start_year=test_year,
            end_year=test_year,
        )

        selected_strategy, train_summary = select_best_strategy(
            train_returns=train_returns,
            metric=selection_metric,
        )

        selected_oos_returns = test_returns[selected_strategy].copy()
        oos_returns.append(selected_oos_returns)

        selection_rows.append(
            {
                "test_year": test_year,
                "train_start_year": train_start_year,
                "train_end_year": train_end_year,
                "selection_metric": selection_metric,
                "selected_strategy": selected_strategy,
                "train_cagr": train_summary.loc[selected_strategy, "cagr"],
                "train_sharpe": train_summary.loc[selected_strategy, "sharpe_ratio"],
                "train_volatility": train_summary.loc[
                    selected_strategy,
                    "annualized_volatility",
                ],
                "train_max_drawdown": train_summary.loc[
                    selected_strategy,
                    "max_drawdown",
                ],
            }
        )

    if not oos_returns:
        raise ValueError("No walk-forward test periods were generated.")

    wf_returns = pd.concat(oos_returns).sort_index()
    wf_returns.name = f"Walk-Forward Selected by {selection_metric}"

    selection_log = pd.DataFrame(selection_rows)

    return wf_returns, selection_log


def build_walk_forward_comparison(
    returns: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Build walk-forward portfolios selected by CAGR and Sharpe.

    Parameters
    ----------
    returns:
        Monthly return matrix.

    Returns
    -------
    tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]
        Walk-forward returns, selection log, performance summary.
    """
    wf_sharpe_returns, sharpe_log = build_walk_forward_portfolio(
        returns=returns,
        selection_metric="sharpe_ratio",
    )

    wf_cagr_returns, cagr_log = build_walk_forward_portfolio(
        returns=returns,
        selection_metric="cagr",
    )

    walk_forward_returns = pd.concat(
        [
            wf_sharpe_returns.rename("Walk-Forward Selected by Sharpe"),
            wf_cagr_returns.rename("Walk-Forward Selected by CAGR"),
            returns.loc[wf_sharpe_returns.index, CANDIDATE_STRATEGIES + BENCHMARKS],
        ],
        axis=1,
    ).dropna()

    selection_log = pd.concat(
        [sharpe_log, cagr_log],
        axis=0,
        ignore_index=True,
    )

    rows = {}

    for column in walk_forward_returns.columns:
        rows[column] = compute_performance_summary(
            returns=walk_forward_returns[column],
            periods_per_year=PERIODS_PER_YEAR,
            turnover=None,
        )

    summary = pd.DataFrame(rows).T

    return walk_forward_returns, selection_log, summary


# ============================================================
# Main
# ============================================================

def main() -> None:
    """
    Run walk-forward validation.
    """
    print("=" * 80)
    print("Walk-forward validation")
    print("=" * 80)

    returns = load_comparison_returns()

    walk_forward_returns, selection_log, summary = build_walk_forward_comparison(
        returns=returns,
    )

    DATA_DIR.mkdir(parents=True, exist_ok=True)

    walk_forward_returns.to_csv(WALK_FORWARD_RETURNS_PATH)
    selection_log.to_csv(WALK_FORWARD_SELECTION_PATH, index=False)
    summary.to_csv(WALK_FORWARD_SUMMARY_PATH)

    print()
    print("Selection log:")
    print(selection_log)

    print()
    print("Raw walk-forward summary:")
    print(summary)

    print()
    print("Formatted walk-forward summary:")
    print(format_performance_summary(summary))

    print()
    print("Saved outputs:")
    print(f"- {WALK_FORWARD_RETURNS_PATH}")
    print(f"- {WALK_FORWARD_SELECTION_PATH}")
    print(f"- {WALK_FORWARD_SUMMARY_PATH}")

    print()
    print("Done.")


if __name__ == "__main__":
    main()